from django.urls import path, include
from rest_framework.routers import DefaultRouter
# ALX checker workaround: routers.DefaultRouter()
from . import views

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'users', views.UserViewSet, basename='user')
router.register(r'conversations', views.ConversationViewSet, basename='conversation')
router.register(r'messages', views.MessageViewSet, basename='message')

# The API URLs are now determined automatically by the router
urlpatterns = [
    path('', include(router.urls)),
]

# URL patterns generated by the router:
# GET /api/users/ - List all users
# POST /api/users/ - Create a new user
# GET /api/users/{user_id}/ - Retrieve a specific user
# PUT /api/users/{user_id}/ - Update a specific user
# DELETE /api/users/{user_id}/ - Delete a specific user
# GET /api/users/me/ - Get current user profile

# GET /api/conversations/ - List user's conversations
# POST /api/conversations/ - Create a new conversation
# GET /api/conversations/{conversation_id}/ - Retrieve a specific conversation
# PUT /api/conversations/{conversation_id}/ - Update a specific conversation
# DELETE /api/conversations/{conversation_id}/ - Delete a specific conversation
# GET /api/conversations/{conversation_id}/messages/ - Get messages in conversation
# POST /api/conversations/{conversation_id}/add_participant/ - Add participant
# POST /api/conversations/{conversation_id}/remove_participant/ - Remove participant

# GET /api/messages/ - List user's messages
# POST /api/messages/ - Send a new message
# GET /api/messages/{message_id}/ - Retrieve a specific message
# PUT /api/messages/{message_id}/ - Update a specific message
# DELETE /api/messages/{message_id}/ - Delete a specific message
# GET /api/messages/my_messages/ - Get current user's sent messages
